### ISSUE TITLE
Replace the 100x100 black preview in DNG

### ISSUE THREAD

**Issue by rolkar** [Kalpanika/x3f#50]
As far as I understand we have a 100x100 black preview in the DNG files. This is annoying. For one, I see those preview images in my explorer.

**Comment by erikrk** [comment]
That's correct. It's present in IFD0. According to the DNG
specification, it's recommended to put a low-resolution preview there.

http://www.adobe.com/content/dam/Adobe/en/products/photoshop/pdfs/dng_spec_1.4.0.0.pdf#G5.1049965

**Comment by rolkar** [comment]
Shall this thumb nail be converted or not?

**Comment by erikrk** [comment]
Is should be converted to RGB. It's primarily ment for software that
doesn't understand DNG.

**Comment by rolkar** [comment]
OK, so a 200x300 or 300x200 or so converted image should be there instead.

**Comment by erikrk** [comment]
I will implement a preview.
