### ISSUE TITLE
Workaround needed for incorrect specification of masked areas in DP2 files

### ISSUE THREAD

**Issue by erikrk** [Kalpanika/x3f#53]
zodiacfml posted this about clipped blacks for DP2.

http://www.dpreview.com/forums/post/56198531

After examining the X3F file sent to me, I have come to the conclusion that DarkShieldBottom is specified incorrectly in DP2 files. It partially coincides with the active image. This leads to overestimation of the black level, and thus clipping. The same occurs with x3f-examples/dp2_a.x3f.

I suppose we could work around this by ignoring DarkShieldBottom for DP2.

**Comment by rolkar** [comment]
One can spevulate in if this is true for all DP2 cameras and if
this might be true for some other cameras.

**Comment by erikrk** [comment]
It's true for at least two DP2 cameras. I have run x3f_extract on all
files in x3f-examples and examined the black levels. The results are
below. dp2_a.x3f could be singled out due to its exceptionally high
standard deviation. I think the rest (except dp2m_error.x3f which is a
broken file) looks reasonable.

Dump RAW as DNG to dp1_a.x3f.dng
black_level = {0.667917,0.655795,0.554962}, black_dev =
{1.04855,1.02064,0.91652}
Dump RAW as DNG to dp1s_a.x3f.dng
black_level = {0.64322,0.638258,0.584318}, black_dev =
{1.03207,0.991925,0.939864}
Dump RAW as DNG to dp1_template_sd15_images.x3f.dng
black_level = {1.0936,1.13231,1.11106}, black_dev =
{1.79977,1.81929,1.7312}
Dump RAW as DNG to dp2_a.x3f.dng
black_level = {47.4344,62.0796,62.7913}, black_dev =
{141.109,186.378,188.981}
Dump RAW as DNG to dp2m_error.x3f.dng
black_level = {31.5852,31.4213,63881}, black_dev =
{3.29158,3.90033,709.026}
Dump RAW as DNG to dp2q-black-1_2000s.x3f.dng
black_level = {2049.12,2047.98,2049.53}, black_dev =
{13.5183,11.5373,8.6247}
Dump RAW as DNG to dp2q-black-1_8s.x3f.dng
black_level = {2049.46,2049.1,2049.34}, black_dev =
{13.4695,11.5676,19.9456}
Dump RAW as DNG to dp2q-overexposed.x3f.dng
black_level = {2050.46,2049.94,2049.35}, black_dev =
{13.5804,11.4409,17.7676}
Dump RAW as DNG to dp2s_a.x3f.dng
black_level = {0.679735,0.675682,0.611402}, black_dev =
{1.23836,1.03768,0.955137}
Dump RAW as DNG to dp2s_b.x3f.dng
black_level = {0.701705,0.707727,0.652917}, black_dev =
{0.992356,0.98101,0.93648}
Dump RAW as DNG to dp3m-black.x3f.dng
black_level = {15.9494,15.8749,16.0392}, black_dev =
{2.49051,2.91435,3.27136}
Dump RAW as DNG to dp3m-overexposed.x3f.dng
black_level = {15.994,15.9032,16.0299}, black_dev =
{2.36757,2.78303,2.47523}
Dump RAW as DNG to sd10_a.x3f.dng
black_level = {260.066,259.978,259.371}, black_dev =
{3.59023,3.29987,3.724}
Dump RAW as DNG to sd10_negative_values.x3f.dng
black_level = {45.7434,46.9075,46.3219}, black_dev =
{3.66776,3.27097,3.5716}
Dump RAW as DNG to sd14_a.x3f.dng
black_level = {722.585,721.951,722.982}, black_dev =
{5.50651,31.3009,5.21115}
Dump RAW as DNG to sd14_b.x3f.dng
black_level = {53.5579,53.9699,53.4652}, black_dev =
{5.3075,5.12166,4.96853}
Dump RAW as DNG to sd15_a.x3f.dng
black_level = {1.0936,1.13231,1.11106}, black_dev =
{1.79977,1.81929,1.7312}
Dump RAW as DNG to sd15_b.x3f.dng
black_level = {1.16458,1.34549,1.01943}, black_dev =
{1.85536,1.9811,1.67283}
Dump RAW as DNG to sd1_a.x3f.dng
black_level = {15.855,15.8751,15.7978}, black_dev =
{2.50376,2.96459,2.1827}
Dump RAW as DNG to sd1_b.x3f.dng
black_level = {15.8121,15.7181,15.8346}, black_dev =
{2.41334,2.82263,2.13925}
Dump RAW as DNG to sd1_c.x3f.dng
black_level = {15.8841,15.8116,15.825}, black_dev =
{2.28129,2.66643,1.98102}
Dump RAW as DNG to sd1_d.x3f.dng
black_level = {15.9245,15.8114,15.8248}, black_dev =
{2.34367,2.74128,2.11175}
Dump RAW as DNG to x530_a.x3f.dng
black_level = {9.89431,6.69259,3.29152}, black_dev =
{13.5592,10.3976,4.8283}
Dump RAW as DNG to dp1m_SDIM0015.X3F.dng
black_level = {31.5898,31.4294,31.6927}, black_dev =
{3.13942,4.3146,1.31934}
Dump RAW as DNG to dp1m_SDIM0027.X3F.dng
black_level = {31.5212,31.4082,31.665}, black_dev =
{3.14433,4.35001,1.52806}
Dump RAW as DNG to dp2m-alusiate-binned-medium.X3F.dng
black_level = {16.2377,15.9032,16.2019}, black_dev =
{2.0323,2.15623,2.50833}
Dump RAW as DNG to dp2m_SDI0141.X3F.dng
black_level = {31.0869,31.1622,31.2023}, black_dev =
{3.24963,4.00453,1.09335}
Dump RAW as DNG to dp2m_SDIM0003.X3F.dng
black_level = {31.228,31.2993,31.2047}, black_dev =
{2.96884,3.43228,1.02482}
Dump RAW as DNG to dp2q-alusiate-binned-low.X3F.dng
black_level = {2047.69,2046.69,2049.52}, black_dev =
{14.6355,12.2334,8.5604}
Dump RAW as DNG to dp2q-beer-garden-1405772202.X3F.dng
black_level = {2047.72,2046.51,2049.27}, black_dev =
{13.4396,11.2892,10.5636}
Dump RAW as DNG to dp2q-beer-garden-1405776566.X3F.dng
black_level = {2048.43,2048.01,2049.27}, black_dev =
{13.368,11.2445,8.78269}
Dump RAW as DNG to dp2q_SDIM0003.X3F.dng
black_level = {2047.98,2047.33,2048.69}, black_dev =
{13.3151,11.3922,8.03599}
Dump RAW as DNG to dp3m-markWW-binned-low.X3F.dng
black_level = {31.2012,31.1326,31.1043}, black_dev =
{1.51229,1.73783,0.489836}
Dump RAW as DNG to sd10-xpatUSA-binned-low.X3F.dng
black_level = {117.797,121.888,120.553}, black_dev =
{5.45853,2.32438,2.62467}
Dump RAW as DNG to sd14-arvo-binned-hi.X3F.dng
black_level = {60.9408,61.2757,61.4366}, black_dev =
{5.29811,5.05484,5.10871}
Dump RAW as DNG to sd14-arvo-binned-low.X3F.dng
black_level = {18.2254,18.5787,18.5248}, black_dev =
{4.21917,4.02714,4.03899}
Dump RAW as DNG to sd14-arvo-binned-med.X3F.dng
black_level = {26.9287,27.6299,27.4251}, black_dev =
{4.71619,4.56103,4.57643}
Dump RAW as DNG to sd1_SDI8226.X3F.dng
black_level = {15.8235,15.8008,15.8074}, black_dev =
{2.46554,2.99706,2.06198}
Dump RAW as DNG to sd1_SDIM7873.X3F.dng
black_level = {15.7721,15.7612,15.9269}, black_dev =
{2.3186,2.80113,2.00711}
Dump RAW as DNG to sd9-xpatUSA-binned-low.X3F.dng
black_level = {252.493,267.852,265.202}, black_dev =
{5.66838,4.7196,5.2926}
