### ISSUE TITLE
Extract separate layers

### ISSUE THREAD

**Issue by rolkar** [Kalpanika/x3f#69]
There are some that think it would be nice to be able to extract raw layers.

http://www.dpreview.com/forums/post/56257813

In particular it is the Merrill top layer that some use for B&W work.

**Comment by erikrk** [comment]
Is this a relevant feature? There is always netpbm/ppmtorbg3 for extracting
layers.

I think a more useful functionalty for B&W work would be generation of
grayscale TIFF using a specified mix including rescaling and gamma, e.g
"x3f_extract -tiff -bw 0.5:0.3:0.1 -gamma 2.2 file.x3f"

**Comment by rolkar** [comment]
It is not a useful feature for us.

It is a feature I have seen at least a couple wanting. Mostly newbies to 
shell/cmd

It is an easy feature to add. But bloating is no fun.

/Roland

**Comment by erikrk** [comment]
I would say layer extraction is an irrelevant feature.

If we should add something, I think it should be proper b&w processing
including mix, rescaling and gamma. I think that's at least what Chris
wanted. To use only to top layer you just have to specify the mix as
0.0:0.0:1.0.

**Comment by rolkar** [comment]
OK

**Comment by rolkar** [comment]
I agree that extracting separate layers is irrelevant. So, I close the issue.
