### ISSUE TITLE
Batch command

### ISSUE THREAD

**Issue by Arn2014** [Kalpanika/x3f#79]
Hi,

I'm fairly new to using the x3f_extract command line tool (I am using it in Terminal on a mac)
how can I run a Batch command to bath process a complete directory with x3f files to .dng?
to another folder in the same directory called for example "batched" 
(camera used is a sigma dp2 quattro) 

Thanks for developing this great tool!

**Comment by mmroden** [comment]
Hi @Arn2014,

Thanks, glad you like it!  Have you tried wildcarding?

That is, you can run the command like so:

x3f_extract *.x3f

Where the '*' is a wildcard that tells the computer to match any file that's named that has the '.x3f' substring.

Please let us know if that works for you.

**Comment by Arn2014** [comment]
Hi mmroden,

I've tried the * wildcard batch run, but somthing goes wrong..
i did a test run on a folder on my desktop with about 20 .X3F files in it..

the batch did only run the first 4 images and gave me the following error

`READ THE X3F FILE DP2Q0217.X3F
WARNING: matrix entry for LUT_HI_RR_x1/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for LUT_HI_RR_x1/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for LUT_LOW_RR_x1/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for LUT_LOW_RR_x1/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_HI_high/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_HI_high/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_LOW_high/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_LOW_high/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_HI_low/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_HI_low/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_LOW_low/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_LOW_low/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LVHD_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LVHD_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LVHD_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LVHD_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_HI/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_HI/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SegmentGains_HI_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SegmentGains_HI_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SegmentGains_HI_BOT/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SegmentGains_HI_BOT/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_AFLV/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_AFLV/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_LV/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_LV/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_LVHD/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_LVHD/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G_3order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G_3order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G_2order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G_2order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G_1order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G_1order/InputVal is out of order (index/0 != order/1)
Dump RAW as DNG to DP2Q0217.X3F.dng
READ THE X3F FILE DP2Q0218.X3F
WARNING: matrix entry for LUT_HI_RR_x1/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for LUT_HI_RR_x1/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for LUT_LOW_RR_x1/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for LUT_LOW_RR_x1/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_HI_high/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_HI_high/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_LOW_high/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_LOW_high/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_HI_low/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_HI_low/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_LOW_low/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_LOW_low/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LVHD_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LVHD_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LVHD_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LVHD_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_HI/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_HI/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SegmentGains_HI_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SegmentGains_HI_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SegmentGains_HI_BOT/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SegmentGains_HI_BOT/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_AFLV/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_AFLV/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_LV/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_LV/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_LVHD/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_LVHD/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G_3order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G_3order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G_2order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G_2order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G_1order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G_1order/InputVal is out of order (index/0 != order/1)
Dump RAW as DNG to DP2Q0218.X3F.dng
READ THE X3F FILE DP2Q0219.X3F
WARNING: matrix entry for LUT_HI_RR_x1/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for LUT_HI_RR_x1/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for LUT_LOW_RR_x1/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for LUT_LOW_RR_x1/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_HI_high/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_HI_high/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_LOW_high/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_LOW_high/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_HI_low/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_HI_low/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for OBGAIN_LOW_low/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for OBGAIN_LOW_low/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LVHD_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LVHD_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LVHD_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LVHD_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_HI/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_HI/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SegmentGains_HI_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SegmentGains_HI_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SegmentGains_HI_BOT/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SegmentGains_HI_BOT/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_AFLV/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_AFLV/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_LV/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_LV/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_LVHD/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_LVHD/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G_3order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G_3order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G_2order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G_2order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G_1order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G_1order/InputVal is out of order (index/0 != order/1)
Dump RAW as DNG to DP2Q0219.X3F.dng`

I have no clue/insight in resolving these warnings or in getting a completed batch run


thanks for any assist!
osx 10.10.5

Regards

**Comment by mmroden** [comment]
Very interesting, @Arn2014.  I'll try to take a look into this shortly.

I think that most of those errors are simply warnings that can be ignored, but only working on 4 out of 20 is not good.

**Comment by Arn2014** [comment]
correction..only the first 3 files did run (they open correctly  in Adobe-Lightroom..)
possibly a process memory issue, limiting or expanding the process memory setting per batch run?

Thanks for looking into this!

+/- 16GB system memory available

regards,

**Comment by rolkar** [comment]
Hi - the printouts are only warning/debug messages, and do not affect the result. We should really suppress those in the general release. People get worried :) NOTE - they might be important in coming releases, but we are not using the meta data that is in the wrong order today.

That you only get 4 images might be a matter of character case.  You might need to run

x3f_extract *.X3F *.x3f

**Comment by Arn2014** [comment]
Thanks for the character suggestion, the batch is running at the moment and all files are 
(although with warning message per file) are getting processed..!

Batch is done: alle files are processed with one error: Could not open infile *.x3f
But that doesn't get me worried;)

What a great tool and the batch processing goes fast, 25pcs of 50mb files in under 5 minutes
outputed .dng files all open fine in Lightroom

One last question , I saw some  use  -denoise  is it needed ? or only aplicable to certain sigma camera models ,not dp2 quattro related?..

Many thanks for the good and quick support , I really  needed this time saver!

Regards,

**Comment by rolkar** [comment]
It seems like the issue is possible to close.
