### ISSUE TITLE
SD Quattro Suport?

### ISSUE THREAD

**Issue by kwmr** [Kalpanika/x3f#80]
It can not be converted in SD Quattro.

**Comment by mmroden** [comment]
Hi @kwmr -- Can you tell us the specific error?  And do you have a file we can try with?

**Comment by rolkar** [comment]
This was to be expected, Sigma changes the format very often. As Mark says, we would very much appreciate X3F files from the sd Quattro.

**Comment by kwmr** [comment]
Hi.
[terminal](https://www.evernote.com/l/AAFEjaACPyVGsJx5u257oB7ocNjxxWCyvkw)
[X3F:sdQuattro](https://www.evernote.com/l/AAHowKzA4Y9DD4q8R6_iVmdVP2BeJXCp_AE)

**Comment by maxwelx64** [comment]
hi.. is it possible to support the sd quattro x3f file?
here is more SDQ x3f file..
[http://www.focus-numerique.com/test-3042/hybride-sigma-sd-quattro-exemples-photos-15.html](url)

**Comment by rolkar** [comment]
Thanx for the file! I have downloded some. Three words of warning though.

1. Our development efforts are currently very low. And ... it might be some (substantial) work to reverse engineer the new format.

2. When it is reverse engineered, then they might also have changed some meta data that we need to understand to make color images from the RAW data.

3. We have not the slightest idea how to interpret the lens data files that are included in the SPP application. So, we do not know how to correct for different lenses. NOTE - we only know that this is very important for Merrill. We do not know if Quattro is as sensitive.

**Comment by rolkar** [comment]
This issue is solved in release 0.55
