### ISSUE TITLE
sd Quattro, Firmware 1.01.01D43

### ISSUE THREAD

**Issue by rabu1** [Kalpanika/x3f#84]
Hello all,

X3F Files from a sd Quattro firmware vers. 1.01.01D43 cannot be converted into TIFF nor DNG. 
I use version 0.55 on windows.

F:\Program Files\x3f_tools\bin>x3f_extract.exe -v  .\SDIM0797.X3F
OpenCL is disabled
READ THE X3F FILE .\SDIM0797.X3F
Loading CAMF of type 5
SETUP CAMF ENTRIES
WARNING: matrix entry for LUT_RR_x1/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for LUT_RR_x1/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for LUT_RR_x2/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for LUT_RR_x2/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for LUT_RR_x4/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for LUT_RR_x4/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI2x_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI2x_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI2x_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI2x_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI4x_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI4x_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HI4x_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HI4x_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV2x_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV2x_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV2x_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV2x_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV4x_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV4x_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_AFLV4x_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_AFLV4x_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV2x_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV2x_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV2x_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV2x_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV4x_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV4x_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_LV4x_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_LV4x_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HILV_TOP/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HILV_TOP/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnOffsets_HILV_BOTTOM/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnOffsets_HILV_BOTTOM/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for ColumnGains_HI/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for ColumnGains_HI/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G1_3order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G1_3order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G1_2order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G1_2order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G1_1order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G1_1order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G2_3order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G2_3order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G2_2order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G2_2order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G2_1order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G2_1order/InputVal is out of order (index/0 != order/1)
WARNING: matrix entry for SpatialColoringCoeff_G2_0order/Channel is out of order (index/1 != order/0)
WARNING: matrix entry for SpatialColoringCoeff_G2_0order/InputVal is out of order (index/0 != order/1)
SETUP CAMF ENTRIES (READY) Found 320 entries
Could not load RAW from .\SDIM0797.X3F
X3F Delete
Files processed: 1      errors: 1

F:\Program Files\x3f_tools\bin>

**Comment by rolkar** [comment]
Thanx for your issue report.

It would be good if you could provide us with an X3F file from that firmware.

**Comment by rabu1** [comment]
I can here max 10 MB File upload. Can I sent you an Email?

**Comment by rabu1** [comment]
here is a link to the X3F

https://1drv.ms/u/s!AkPTGEvasHQMhERtERQ78_3lUSD9

Another user has the same firmware but by him it works (a raster with small black dots is visible).

**Comment by rabu1** [comment]
Hi,
here is the picture with the  black dot raster from the other user

http://www.dslr-forum.de/attachment.php?attachmentid=3609334&d=1473590102

**Comment by rolkar** [comment]
I have now tried, both with Linux and Windows versions to reproduce the problem. But, it works for me all the time. Can you please try again? And make very sure you are using 0.55.

**Comment by rolkar** [comment]
BTW - the black dot raster we know what it is. It is the AF points on the sensor. We need to interpolate them.

**Comment by rabu1** [comment]
Hi,
thanks for the fast answer.
I download the 32 bit binary and it works. Then I download the 32 bit binary again and it works now too. 
It is crazy.
Thanks again a lot for the fast response.

**Comment by rolkar** [comment]
Not a bug
