### ISSUE TITLE
Black Dots Array in both tiff and dng for sd quattro

### ISSUE THREAD

**Issue by jianghanpeng** [Kalpanika/x3f#89]
![git_01](https://cloud.githubusercontent.com/assets/17606598/18735872/4caa4de0-804f-11e6-83d1-fb24bf8f5ee5.PNG)

As you can see in the attached file, after I convert the x3f file to dng and zoom in to 100%, I can see black dots array in the picture when I open it in CameraRAW. If I convert the x3f into tif, the problem still exist. Is this normal?

Both the x3f and dng:
https://1drv.ms/f/s!AkqkrbwwjG27-DWWVYGNnWVrbQW5

**Comment by kwmr** [comment]
I also check the black dot in the picture after the conversion.

**Comment by rolkar** [comment]
We know about the dots. It is AF dots. We will fix it.

**Comment by calebistaken** [comment]
Hi, when do you expect to release a new version with this fix?

**Comment by rolkar** [comment]
We are working on it. The dp Quattro had a setting in meta data describing the position of the over exposure dots. We cannot find any such info in sd Quattro for the AF dots. The discussion right now is if we shall hard code the positions. Ugly, but maybe the only solution. Have patience! There will be a solution soon, ugly or not.

**Comment by calebistaken** [comment]
Thank's for the assurance.

**Comment by brianandcamera** [comment]
I don't suppose a random assortment of X3F files would help in any way? :/ 

If so, I can provide a handful

**Comment by rolkar** [comment]
Thanx for the offer. We have what we need for fixing this problem.
