### ISSUE TITLE
SD Quattro firmware 1.04 error

### ISSUE THREAD

**Issue by kwmr** [Kalpanika/x3f#95]
After updating the SD Quattro firmware to 1.04, an error will occur during conversion of the taken X3F file to DNG.

Something happened while processing the image.  Error code: 1 argument list: [-compress, /Users/xxxxxxx.X3F]

**Comment by rolkar** [comment]
Hi, thank you for the report.
It would be nice if you can provide us with a file that has the problem.

**Comment by kwmr** [comment]
OK.
https://www.dropbox.com/s/r7ctuu5p98d3ey0/SDQ_5261.X3F?dl=0
Please download from the link above.

**Comment by rolkar** [comment]
Thanx, I have downloaded it. Ill take a look ASAP.

What firmware version is it?

**Comment by kwmr** [comment]
http://www.sigma-global.com/en/download/cameras/firmware/#sd
1.04 latest version

**Comment by J212** [comment]
Hi, I have the same error after updating to firmware 1.04 on my SD Quattro.
The latest firmware 1.05 also results in the same error.

Thank you for the effort!!

**Comment by rolkar** [comment]
Hi, I have had too much to do and also been ill. But - I see the light at the ned of the tunnel. Hopefully, I will look into it soon.

I will also open an issue regarding sd Quattro H. It cannot work properly, and needs to be fixed.

**Comment by J212** [comment]
Hi rolkar, Thank you very much for the great work and effort. You and your team's work made X3F much more usable, particularly with Capture One. Much appreciated!!

Hope you will get well soon too! :)

**Comment by rolkar** [comment]
I have found the problem.

They have removed the meta information for the dark shields used for dark level detection.

Currently, I have no idea how to fix that. We need to be able to detect the dark level. Otherwise, the colors will be way off.

The main question is. Why do they do this strange stuff with the format? Just to annoy?

**Comment by J212** [comment]
Argh! It is so sad to hear that!
And what makes it even more annoying is: they have just released a new firmware 2.0 for DP Quattro series. I think it will have the same problem.

I think it is better not to update the firmware from now on :(

**Comment by rolkar** [comment]
We have found a solution. It is a bit messy to implement.

They have four areas for calculating the black level: top, bottom, left and right.
We have only used top and bottom. Missed left and right :)
Now, they have removed top and bottom :(
But - the left and right are still there :)

The problem being that left and right are not represented as rectangles, but rather columns.
So, we cannot just plug it in to our current code.
Some refactoring is needed. A bit messy to get nice looking.

Stay tuned.

**Comment by rolkar** [comment]
Ah - about the 2.0 firmware. Would need files from that :)
But - there we have a camera ...

**Comment by J212** [comment]
Very glad to hear that!! And looking forward to it!!!
Thanks so much again for you guys' great work!! :)

**Comment by rolkar** [comment]
There is now a pull request #99 that works for this file. It needs to be reviewed by Erik to see if there is something wrong first. The solution is also a bit strange, but so is the choice by Sigma to use a column array to define two rects. So, maybe it is hard to find anything more beautiful.

**Comment by J212** [comment]
Hi, is there any update of the development?

**Comment by rolkar** [comment]
Yes, it is fixed. The fix is on master right now. But, unfortunately the fixing of the code got mixed with the implementation of Quattro H. And ... Quattro H is also sort of working, except that the black level computation is way off. Something we have been struggling with fixing. Therefore, the next release has been delayed.

If you can compile the code, you can use the master branch right now. It should work for Quattro.

**Comment by J212** [comment]
Hi rolkar, 
Thank you for the effort of you and your team. Unfortunately, I'm not familiar with command lines. I will patiently wait for the next update of x3f wrapper  :) Thanks again!

**Comment by mmroden** [comment]
Given that the current state of master is one-step-forward, one-step-back, I was gonna hold off on the wrapper for now.

**Comment by rolkar** [comment]
The current master is probably the best commit so far. It would be an improvement to release i, except ... the sd Quattro H implementation has a serious problem, it cannot find the correct black point.

So .... my thoughts goes like this. If we cannot find a good solution to the black point problem (which actually is a general problem) within a reasonable time, then we better release the current master, with the caveat that the black point for H is off.

Marc, Ill describe the problem in a mail conversation with you and Erik and we can see if we can come up with something sensible.

**Comment by rolkar** [comment]
Solved in release 0.57
