### ISSUE TITLE
sd Quattro H

### ISSUE THREAD

**Issue by rolkar** [Kalpanika/x3f#96]
We have not tested with sd Quattro H. But, it cannot work properly, as the AF grid is hard coded.

Would be nice to find the data that defines the grid, in order to make the code portable to next sensor.

Anyhow, need an X3F file from sd Quattro H, so we can fix it.

**Comment by hanickadot** [comment]
Quattro H is not working at all. 

`x3f_extract -v /Users/hanka/Pictures/sdh/2017-04-24/SDQH5070.X3F   
   : X3F TOOLS VERSION = 0.56-osx-x86_64

dbg: OpenCL is disabled
   : READ THE X3F FILE /Users/hanka/Pictures/sdh/2017-04-24/SDQH5070.X3F
dbg: Loading CAMF of type 5
dbg: SETUP CAMF ENTRIES
dbg: Matrix entry for LUT_RR_x1/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for LUT_RR_x1/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for LUT_RR_x2/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for LUT_RR_x2/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for LUT_RR_x4/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for LUT_RR_x4/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_HI_TOP/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_HI_TOP/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_HI_BOTTOM/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_HI_BOTTOM/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_HI2x_TOP/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_HI2x_TOP/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_HI2x_BOTTOM/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_HI2x_BOTTOM/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_HI4x_TOP/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_HI4x_TOP/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_HI4x_BOTTOM/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_HI4x_BOTTOM/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_AFLV_TOP/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_AFLV_TOP/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_AFLV_BOTTOM/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_AFLV_BOTTOM/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_AFLV2x_TOP/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_AFLV2x_TOP/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_AFLV2x_BOTTOM/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_AFLV2x_BOTTOM/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_AFLV4x_TOP/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_AFLV4x_TOP/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_AFLV4x_BOTTOM/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_AFLV4x_BOTTOM/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_LV_TOP/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_LV_TOP/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_LV_BOTTOM/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_LV_BOTTOM/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_LV2x_TOP/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_LV2x_TOP/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_LV2x_BOTTOM/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_LV2x_BOTTOM/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_LV4x_TOP/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_LV4x_TOP/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_LV4x_BOTTOM/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_LV4x_BOTTOM/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_HILV_TOP/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_HILV_TOP/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnOffsets_HILV_BOTTOM/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnOffsets_HILV_BOTTOM/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for ColumnGains_HI/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for ColumnGains_HI/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for SpatialColoringCoeff_G1_3order/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for SpatialColoringCoeff_G1_3order/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for SpatialColoringCoeff_G1_2order/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for SpatialColoringCoeff_G1_2order/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for SpatialColoringCoeff_G1_1order/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for SpatialColoringCoeff_G1_1order/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for SpatialColoringCoeff_G2_3order/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for SpatialColoringCoeff_G2_3order/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for SpatialColoringCoeff_G2_2order/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for SpatialColoringCoeff_G2_2order/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for SpatialColoringCoeff_G2_1order/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for SpatialColoringCoeff_G2_1order/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for SpatialColoringCoeff_G2_0order/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for SpatialColoringCoeff_G2_0order/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for StillFPPDGain_B1/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for StillFPPDGain_B1/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for StillFPPDGain_B3/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for StillFPPDGain_B3/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for AFFPPDGain_F1B1/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for AFFPPDGain_F1B1/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for AFFPPDGain_F3B3/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for AFFPPDGain_F3B3/InputVal is out of order (index/0 != order/1)
dbg: Matrix entry for AFFPPDGain_F1F3/Channel is out of order (index/1 != order/0)
dbg: Matrix entry for AFFPPDGain_F1F3/InputVal is out of order (index/0 != order/1)
dbg: SETUP CAMF ENTRIES (READY) Found 303 entries
ERR: Could not load RAW from /Users/hanka/Pictures/sdh/2017-04-24/SDQH5070.X3F
dbg: X3F Delete
   : Files processed: 1	errors: 1
`

**Comment by hanickadot** [comment]
I can provide black and white x3f SDH raws.

**Comment by rolkar** [comment]
Thanx. Would be nice if you could provide us with an H file. Preferably one with the latest firmware.

**Comment by rolkar** [comment]
BW?

The RAW data is never BW. The JPEG might be though.

**Comment by hanickadot** [comment]
I mean complete black and complete white. And one normal picture. I'm uploading it now.

**Comment by hanickadot** [comment]
http://tmp.hanicka.net/sdh-raws.zip

**Comment by rolkar** [comment]
Thanx, I will fetch them this evening when home.

**Comment by hanickadot** [comment]
Oh I forgot, it's current firmware 1.01.

**Comment by mmroden** [comment]
@hanickadot do you mind if we include your image in our test suite, to make sure we don't get regressions?  The images are here: https://github.com/Kalpanika/x3f_test_files

**Comment by hanickadot** [comment]
No problem, it's ok.

**Comment by rolkar** [comment]
This issue is now fixed!
